import React from "react";
import { AdminDashboardPage } from "@/pages/admin/AdminDashboardPage";
import { AdminProductsPage } from "@/pages/admin/AdminProductsPage";
import { AdminAddProductPage } from "@/pages/admin/AdminAddProductPage";
import { AdminBulkUploadPage } from "@/pages/admin/AdminBulkUploadPage";
import { AdminCategoriesPage } from "@/pages/admin/AdminCategoriesPage";
import { AdminBrandsPage } from "@/pages/admin/AdminBrandsPage";
import { AdminColorsPage } from "@/pages/admin/AdminColorsPage";
import { AdminSizesPage } from "@/pages/admin/AdminSizesPage";
import { AdminBannersPage } from "@/pages/admin/AdminBannersPage";
import { AdminOrdersPage } from "@/pages/admin/AdminOrdersPage";
import { AdminIncompleteOrdersPage } from "@/pages/admin/AdminIncompleteOrdersPage";
import { AdminReturnsPage } from "@/pages/admin/AdminReturnsPage";
import { AdminReviewsPage } from "@/pages/admin/AdminReviewsPage";
import { AdminCustomersPage } from "@/pages/admin/AdminCustomersPage";
import { AdminPartnersPage } from "@/pages/admin/AdminPartnersPage";
import { AdminFraudPage } from "@/pages/admin/AdminFraudPage";
import { AdminUsersPage } from "@/pages/admin/AdminUsersPage";
import { AdminActivityPage } from "@/pages/admin/AdminActivityPage";
import { AdminSettingsPage } from "@/pages/admin/AdminSettingsPage";

export const renderAdminRoute = (route: string, navigate: (r: string) => void) => {
  if (route === "admin") return <AdminDashboardPage navigate={navigate} />;
  if (route === "admin/products") return <AdminProductsPage navigate={navigate} />;
  if (route === "admin/add-product") return <AdminAddProductPage navigate={navigate} />;
  if (route === "admin/bulk-upload") return <AdminBulkUploadPage navigate={navigate} />;
  if (route === "admin/categories") return <AdminCategoriesPage />;
  if (route === "admin/brands") return <AdminBrandsPage />;
  if (route === "admin/colors") return <AdminColorsPage />;
  if (route === "admin/sizes") return <AdminSizesPage />;
  if (route === "admin/banners") return <AdminBannersPage />;
  if (route === "admin/orders") return <AdminOrdersPage navigate={navigate} />;
  if (route === "admin/incomplete-orders") return <AdminIncompleteOrdersPage navigate={navigate} />;
  if (route === "admin/returns") return <AdminReturnsPage />;
  if (route === "admin/reviews") return <AdminReviewsPage />;
  if (route === "admin/customers") return <AdminCustomersPage />;
  if (route === "admin/partners") return <AdminPartnersPage />;
  if (route === "admin/fraud") return <AdminFraudPage />;
  if (route === "admin/users") return <AdminUsersPage />;
  if (route === "admin/activity") return <AdminActivityPage />;
  if (route === "admin/settings") return <AdminSettingsPage />;
  return null;
};
