export const SITE_CONFIG = {
  name: "Techno World BD",
  bengaliName: "টেকনো ওয়ার্ল্ড বিডি",
  domain: "https://technoworldbangladesh.com",
  phone: "01351003958",
  whatsapp: "+8801351009358",
  whatsappLink: "https://wa.me/8801351009358",
  whatsappChannel: "https://whatsapp.com/channel/0029VbCnUmS2UPBEy3CSGP3O",
  telegram: "https://t.me/technoworldbd1",
  email: "dubaiwholesalebd@gmail.com",
  address: "আদর্শ সদর, কুমিল্লা, বাংলাদেশ",
  wholesaleMinPieces: 10,
  warrantyText: "পণ্য হাতে পাওয়ার পর ২ সপ্তাহ ওয়ারেন্টি",
  deliveryDuration: "১০–১৫ দিনের মধ্যে দ্রুত ডেলিভারি",
  sources: "Dubai / Hong Kong / Russia",
  developer: {
    name: "Jainal Abedin",
    role: "CEO, Dream Career IT BD",
    portfolioUrl: "https://dcitbd.github.io/Jainal-Abedin/",
    companyUrl: "https://dcitbd.github.io/dcitbd",
  },
  socialLinks: [
    { platform: "Facebook", url: "https://www.facebook.com/dubaiwholesalebd", handle: "@dubaiwholesalebd" },
    { platform: "Telegram", url: "https://t.me/technoworldbd1", handle: "technoworldbd1" },
    { platform: "WhatsApp", url: "https://whatsapp.com/channel/0029VbCnUmS2UPBEy3CSGP3O", handle: "Official Channel" },
    { platform: "Instagram", url: "https://www.instagram.com/preorderinbd/", handle: "@preorderinbd" },
    { platform: "TikTok", url: "https://www.tiktok.com/@technoworldbd", handle: "@technoworldbd" },
    { platform: "YouTube", url: "https://www.youtube.com/@technoworldbd1", handle: "@technoworldbd1" },
  ],
  marketplaces: [
    { platform: "Daraz", url: "https://www.daraz.com.bd/shop/aqtnohvn", status: "Active" },
    { platform: "Bikroy", url: "https://bikroy.com/shop/technoworldbd", status: "Active" },
    { platform: "othoba", url: "https://othoba.com/techno-world-bd", status: "Active" },
    { platform: "Cartup", url: "https://cartup.com/shop/techno-world-bd", status: "Active" },
    { platform: "Facebook Shop", url: "https://www.facebook.com/technoworlbd", status: "Active" },
    { platform: "Facebook Marketplace", url: "https://www.facebook.com/marketplace/profile/61586325884520/", status: "Active" },
    { platform: "ClickBD", url: "https://www.clickbd.com/classifieds/sell#", status: "Active" },
  ]
};
